# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "rules_dev.yml"
   - "rules_stage.yml"
   - "rules_utility.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  #- job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

   # static_configs:
    #  - targets: ['localhost:9090']

  - job_name: 'dev_ec2_instances'
    ec2_sd_configs:
      - region: us-gov-west-1
        access_key: <access_key>
        secret_key: <secrte_key>
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Environment]
        regex: 'dev.*'
        action: 'keep'
     # Use the instance tag as the instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: 'stage_ec2_instances'
    ec2_sd_configs:
      - region: us-gov-west-1
        access_key: <access_key>
        secret_key: <secrte_key>
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Environment]
        regex: 'stage.*'
        action: 'keep'
     # Use the instance tag as the instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: 'utility_ec2_instances'
    ec2_sd_configs:
      - region: us-gov-west-1
        access_key: <access_key>
        secret_key: <secrte_key>
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Environment]
        regex: 'utility.*'
        action: 'keep'
     # Use the instance tag as the instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  #- job_name: 'federate'
  #  scrape_interval: 60s
  #  honor_labels: true
  #  metrics_path: '/federate'
  #  params:
  #      'match[]':
  #        - '{job="myservice"}'
  #  static_configs:
  #      - targets:
  #        - '10.247.80.5:9090'
  - job_name: 'consul'
    static_configs:
      - targets: ['10.247.81.26:9102']
        labels: {'host': 'consul1'}
      - targets: ['10.247.81.124:9102']
        labels: {'host': 'consul2'}
      - targets: ['10.247.81.44:9102']
        labels: {'host': 'consul3'}

