version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./docker/prometheus.yml:/etc/prometheus/prometheus.yml"

  consul:
    image: consul:1.2.1
    ports:
      - "8500:8500"
    volumes:
      - "./docker/consul.json:/consul/config/telemetry.json"
  
  vault:
    image: vault:0.10.3
    ports:
      - "8200:8200"
    volumes:
      - "./docker/vault.hcl:/vault/config/vault.hcl"
  
  statsd:
    image: prom/statsd-exporter
    ports:
      - "9102:9102"
      - "9125:9125"
      - "9125:9125/udp"
    # volumes:
    #   - "./docker/statsd-mapping.conf:/tmp/statsd-mapping.conf"
    # command: "-statsd.mapping-config=/tmp/statsd-mapping.conf"