version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./docker/prometheus.yml:/etc/prometheus/prometheus.yml"

  consul:
    image: consul:1.2.1
    ports:
      - "8500:8500"
    volumes:
      - "./docker/consul.json:/consul/config/telemetry.json"