groups:
- name: ec2_instances.rules
  rules:
  - alert: UtilityInstanceDown
    expr: up{job="utility_ec2_instances"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 5 minutes."
  - alert: UtilityLowDiskSpace
    expr: node_filesystem_avail{fstype=~"(ext.|xfs)",job="utility_ec2_instances"} / node_filesystem_size{fstype=~"(ext.|xfs)",job="utility_ec2_instances"} * 100 <= 10
    for: 15m
    labels:
      severity: warn
    annotations:
      title: 'Less than 10% disk space left'
      description: |
        Consider sshing into the instance and removing old logs, clean
        temp files, or remove old apt packages with `apt-get autoremove`
      runbook: troubleshooting/filesystem_alerts.md
      value: '{{ $value | humanize }}%'
      device: '{{ $labels.device }}%'
      mount_point: '{{ $labels.mountpoint }}%'
  - alert: UtilityHighCPU
    expr: instance:node_cpu_in_use:ratio{environment=~"prd|cny"} > 0.8
    for: 10m
    labels:
      severity: critical
    annotations:
      description: CPU use percent is extremely high on {{ if $labels.fqdn }}{{ $labels.fqdn
        }}{{ else }}{{ $labels.instance }}{{ end }} for the past 10 min.

