groups:
- name: ec2_instances.rules
  rules:
  - alert: UtilityInstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 5 minutes."
  - alert: LowDiskSpaceCrit
    expr: node_filesystem_avail{fstype=~"(ext.|xfs)"} / node_filesystem_size{fstype=~"(ext.|xfs)"} * 100 <= 10
    for: 15m
    labels:
      severity: critical
    annotations:
      title: 'Less than 20% disk space left'
      description: |
        Consider sshing into the instance and removing old logs, clean
        temp files, or remove old apt packages with `apt-get autoremove`
      value: '{{ $value | humanize }}%'
      device: '{{ $labels.device }}%'
      mount_point: '{{ $labels.mountpoint }}%'
  - alert: LowDiskSpaceWarn
    expr: node_filesystem_avail{fstype=~"(ext.|xfs)"} / node_filesystem_size{fstype=~"(ext.|xfs)"} * 100 <= 20
    for: 15m
    labels:
      severity: warning
    annotations:
      title: 'Less than 10% disk space left'
      description: |
        Consider sshing into the instance and removing old logs, clean
        temp files, or remove old apt packages with `apt-get autoremove`
      value: '{{ $value | humanize }}%'
      device: '{{ $labels.device }}%'
      mount_point: '{{ $labels.mountpoint }}%'
  - alert: HighCPU
    expr: instance:node_cpu_in_use:ratio{environment=~"prd|cny"} > 0.8
    for: 5m
    labels:
      severity: critical
    annotations:
      description: CPU use percent is extremely high on {{ if $labels.fqdn }}{{ $labels.fqdn
        }}{{ else }}{{ $labels.instance }}{{ end }} for the past 5 min.
  - alert: NodeSwapUsage
    expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 75
    for: 10m
    labels:
      severity: critical
    annotations:
      description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"
  - alert:  NodeMemoryUsage
    expr: (sum(node_memory_MemTotal) - sum(node_memory_MemFree + node_memory_Buffers + node_memory_Cached) ) / sum(node_memory_MemTotal) * 100 > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"

